# Generated by Django 5.0.6 on 2024-07-06 22:54

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learningApp', '0003_course_enrolled'),
    ]

    operations = [
        migrations.CreateModel(
            name='lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('number', models.IntegerField(validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)])),
                ('have_quiz', models.CharField(choices=[('True', 'True'), ('False', 'False')], max_length=10)),
                ('content', models.TextField()),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learningApp.course')),
            ],
        ),
        migrations.CreateModel(
            name='quize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
                ('answer1', models.CharField(max_length=100)),
                ('answer2', models.CharField(max_length=100)),
                ('answer3', models.CharField(max_length=100)),
                ('correct', models.CharField(max_length=100)),
                ('lesson', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='learningApp.lesson')),
            ],
        ),
    ]
