# Generated by Django 5.0.6 on 2024-07-07 16:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learningApp', '0004_lesson_quize'),
    ]

    operations = [
        migrations.AddField(
            model_name='course_enrolled',
            name='quiz',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='course_enrolled',
            name='progress',
            field=models.FloatField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
    ]
